name: CMS deploy to DEV
on:
  workflow_dispatch:
    inputs:
      DEPLOY_OR_FALLBACK:
        type: choice
        description: Deploy or Fallback
        options:
        - DP
        - FB

jobs:
  _Init_:
    name: Checkout
    runs-on: ${{ vars.RUNS_ON }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set CMS workflow component values
        id: set-cms-workflow-component-values
        run: |
          content=$(jq -n --compact-output --arg buildRunner "${{ vars.CMS_COMPONENT_RUNNER_NAME }}" '$ARGS.named')
          echo "content=$content" >> $GITHUB_OUTPUT
        shell: bash
